services:
  server-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: server-test
    env_file:
      - .env.test
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: test
    ports:
      - ${PORT}:3000
    depends_on:
      db_test:
        condition: service_healthy
  db_test:
    image: postgres:15
    restart: always
    container_name: server-test-db
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${EXPOSE_POSTGRES_PORT}:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata-test:
