services:
  server-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server-dev
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: dev
    ports:
      - ${PORT}:3000
    depends_on:
      db_dev:
        condition: service_healthy
  db_dev:
    image: postgres:15
    restart: always
    container_name: server-dev-db
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${EXPOSE_POSTGRES_PORT}:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata-dev:
