version: '1.0'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: server
    env_file:
      - .env.prod
    environment:
      NODE_ENV: prod
    ports:
      - ${PORT}:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "${EXPOSE_POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
